version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./model_random_forest.pkl:/app/model_random_forest.pkl
      - .:/app
    env_file:
      - .env
